[env:uno_r4_minima]
platform      = renesas-ra
board         = uno_r4_minima
framework     = arduino
monitor_speed = 230400
upload_speed  = 230400
build_flags   =
  -D SAMPLE_RATE=500
  -D N_CHANNELS=3
  -D BAUD_RATE=230400
